#!/bin/bash
cd $HOME

# Install nord dircolors
curl -fsSL https://github.com/arcticicestudio/nord-dircolors/raw/develop/src/dir_colors > .dir_colors

# Init submodules
yadm submodule update --recursive --init

# Install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended

# Install zsh syntax highlighting and suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
