[General]
__userfile__=true
backlightIdleness=50
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=true
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=1
iconType=0
idlenessACAction=-2
idlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessBatteryAction=4
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\x4\x93\xe0)
lidClosedAcAction=-2
lidClosedAction=4
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
monitorIdlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
monitorIdlenessBatteryTime=@Variant(\0\0\0\xf\0\0\xea`)
powerKeyAction=3
powerLowAction=4
powerLowLevel=5
powerLowWarning=60
runCheckLevel=1
showIcon=false
suspendKeyAction=4
